
version: "3.7"

services:
  mariadb:
    image: mariadb:10.5.10
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - 3307:3306
    volumes:
      - mariadbdata:/var/lib/mysql
volumes:
  mariadbdata: